### ISSUE TITLE
walking off the overworld (is possible and) raises an exception

### ISSUE THREAD

**Issue by t34lbytes** [InspectorCaracal/evennia-minimud#9]
If I leave the town and head north, I reach the water.  If I keep going north I get stack traces that indicate an array out of bounds exception in creating a new room at the new location, which is clearly outside the map.

```
2024-04-05 21:17:49 [!!] Traceback (most recent call last):
2024-04-05 21:17:49 [!!]   File "mud-prep/venv/lib/python3.11/site-packages/evennia/commands/cmdhandler.py", line 628, in _run_command
2024-04-05 21:17:49 [!!]     ret = cmd.func()
2024-04-05 21:17:49 [!!]           ^^^^^^^^^^
2024-04-05 21:17:49 [!!]   File "mud-prep/venv/lib/python3.11/site-packages/evennia/objects/objects.py", line 3193, in func
2024-04-05 21:17:49 [!!]     self.obj.at_traverse(self.caller, self.obj.destination)
2024-04-05 21:17:49 [!!]   File "mud-prep/evennia-minimud/typeclasses/exits.py", line 86, in at_traverse
2024-04-05 21:17:49 [!!]     super().at_traverse(traveller, destination, **kwargs)
2024-04-05 21:17:49 [!!]   File "mud-prep/venv/lib/python3.11/site-packages/evennia/contrib/grid/wilderness/wilderness.py", line 719, in at_traverse
2024-04-05 21:17:49 [!!]     traversing_object.location.msg_contents(
2024-04-05 21:17:49 [!!]   File "mud-prep/venv/lib/python3.11/site-packages/evennia/objects/objects.py", line 972, in msg_contents
2024-04-05 21:17:49 [!!]     {
2024-04-05 21:17:49 [!!]   File "mud-prep/venv/lib/python3.11/site-packages/evennia/objects/objects.py", line 973, in <dictcomp>
2024-04-05 21:17:49 [!!]     key: obj.get_display_name(looker=receiver)
2024-04-05 21:17:49 [!!]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 21:17:49 [!!]   File "mud-prep/venv/lib/python3.11/site-packages/evennia/contrib/grid/wilderness/wilderness.py", line 615, in get_display_name
2024-04-05 21:17:49 [!!]     name = self.location_name
2024-04-05 21:17:49 [!!]            ^^^^^^^^^^^^^^^^^^
2024-04-05 21:17:49 [!!]   File "mud-prep/venv/lib/python3.11/site-packages/evennia/contrib/grid/wilderness/wilderness.py", line 495, in location_name
2024-04-05 21:17:49 [!!]     return self.wilderness.mapprovider.get_location_name(self.coordinates)
2024-04-05 21:17:49 [!!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-05 21:17:49 [!!]   File "mud-prep/evennia-minimud/world/maps/overworld.py", line 129, in get_location_name
2024-04-05 21:17:49 [!!]     tile = rows[y][x]
2024-04-05 21:17:49 [!!]            ~~~~~~~^^^
2024-04-05 21:17:49 [!!] IndexError: string index out of range
2024-04-05 21:17:49 [EE] User input was: 'n'.

```

I thought I could fix it by just adding this to `typeclasses/exit.py` to the `OverWorldExit` class:

```
    def at_traverse_coordinates(self, traveller, coordinates, new_coordinates, **kwargs):
        return self.location.wilderness.is_valid_coordinates(new_coordinates)
```

And while it does prevent the player from moving and prevent the stack trace, nothing tells the player that they're trying to move to a place they can't move.  (I also don't know if this will cause other problems.)  So then it occurred to me that maybe the exit shouldn't have been created on an area of the map where you can't traverse in that direction, but I haven't looked into how those pieces work yet.

This was with the latest master (06812187bdd096ace4675afcc122d75d68533470) and whatever version of evennia was pip installed... (4.0.0 dist?)

**Comment by t34lbytes** [comment]
> Exits on a room are always present, but locks hide those not used for a
> location. So make sure to `quell` if you are a superuser (since the superuser ignores
> locks, those exits will otherwise not be hidden)

Oh,
